apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    type: front-end
    region: prod
spec:
  template:
    metadata:
      name: web
      labels:
        type: front-end
        region: prod
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: web
        image: gautham990/devops:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        resources:
          requests:
            memory: 128Mi
            cpu: 250m
          limits:
            memory: 256Mi
            cpu: 300m
  replicas: 2
  selector:
    matchLabels:
      type: front-end
      region: prod
